/*
 * generated by Xtext
 */
package org.xtext.example.awesomedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AwesomeDSLUiModule extends org.xtext.example.awesomedsl.ui.AbstractAwesomeDSLUiModule {
	public AwesomeDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
