/*
 * generated by Xtext
 */
package org.xtext.example.awesomedsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AwesomeDSLStandaloneSetup extends AwesomeDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new AwesomeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

